#!/usr/bin/env python

import sys, os, json, tempfile, shutil, subprocess
from uuid import uuid4
from jinja2 import Template

## Detect if chrome or brave is installed
programs = ["chrome", "brave", "google-chrome", "google-chrome-stable"]
browser = None

for program in programs:
    if shutil.which(program) is not None:
        browser = program
        break 

if browser is None:
    print("Please install one of the following programs:", ",".join(programs))
    sys.exit(0)

task_md = os.path.realpath(sys.argv[1])
root = os.path.dirname(task_md)
task_json = os.path.join(root, os.path.splitext(task_md)[0] + '.json')
task_pdf = os.path.join(root, os.path.splitext(task_md)[0] + '.pdf')
task_info = json.loads(open(task_json, 'r').read())
script_dir = os.path.dirname(os.path.realpath(__file__))

# Render PDF Template
template_html = os.path.join(script_dir, "template.html")
with open(template_html) as f:
    template = Template(f.read())

context = {
    'content': open(task_md, 'r').read().encode().decode('utf-8'),
    'task_name': task_info['task_name'],
    'contest': task_info['contest'],
    'language': task_info['language'],
    'images_path': root,
    'static_path': os.path.join(script_dir, 'static'),
}

# Make PDF
html = template.render(context)
html_path = os.path.join(root, '.{}.html'.format(str(uuid4())))

with open(html_path, 'wb') as f:
    f.write(html.encode('utf-8'))

subprocess.call([browser, 
    "-headless", 
    "--disable-cpu",
    "--print-to-pdf={}".format(task_pdf), 
    "--disable-extensions",
    "--print-to-pdf-no-header",
    "--disable-popup-blocking", 
    "--run-all-compositor-stages-before-draw"
    "--disable-checker-imaging", 
    html_path])
os.remove(html_path)

# Add footer
color = '-color "0.4 0.4 0.4" '
subprocess.call(['cpdf', 
    "-add-text", "\"{0} (%Page of %EndPage)   \"".format(task_info['task_name']), 
    "-font", "\"Arial\"", 
    "-color", "010102", 
    "-font-size", "10", 
    "-bottomright", ".62in",
    task_pdf,
    "-o", task_pdf])

# cmd = ('cpdf -add-text "{0} (%Page of %EndPage)   " -font "Arial" ' + '-color "0.4 0.4 0.4" ' +
#       '-font-size 10 -bottomright .62in "{1}" -o "{1}"').format(os.path.join(script_dir, 'cpdf', 'cpdf'), task_info['task_name'].capitalize(), task_pdf)
# os.system(cmd)
